# Randint vs Randn
Randint returns a random integer from  a distrcret uniform distribution from low to high. Random.randint(a,b), where a <= N <= b

In [48]:
#numpy.random.randint(low, high=None, size=None, dtype='l')

Randn returns a sample from the standard normal distribution. It can also be used to creats an array of a given shape and filled with random float from normal distribution.

In [49]:
#numpy.random.randn(d0, d1, ..., dn)

In [50]:
import numpy as np

# Randint

In [51]:
#randint(low, high=optional, size)

np.random.randint(100,size=1)

#Pick 10 numbers in the upper bound of 50
np.random.randint(50,size=10)

#Create a 2x4 array in the upper bound of 10
np.random.randint(10, size=(2,4))

#1x3 arrary with 3 differnt upper bounds. Lower bound is 1, and the hieghtest these three can go is in the list
np.random.randint(1, [3, 5, 10])

#1x3 arrary with 3 differnt lower bounds. Lower bound of the three is in the list, while 20 is the upper bound
np.random.randint([4, 5, 10],20)

array([10, 16, 12])

# Randn

In [52]:
np.random.randn()

1.9090713043047494

In [53]:
np.random.rand(5)

array([0.93775279, 0.75757811, 0.87747562, 0.23167922, 0.07719149])

In [54]:
#2D arry that is 5x5
np.random.randn(5,5)

array([[-0.13022402,  0.490232  , -2.94648775,  1.71571313,  0.76991798],
       [-0.24386684,  0.33732042,  0.26688151,  0.29559922, -0.50126306],
       [ 0.38767889,  0.28464286, -0.1929684 ,  0.29466071,  0.78709673],
       [ 0.48345047,  0.52641548, -0.53471111,  0.73661464, -1.50129034],
       [ 0.57232697, -1.81169934, -0.50833843, -0.38104334, -1.88282081]])

In [55]:
#3D array with two datafram that is 3x4
np.random.randn(2,3,4)

array([[[ 0.48490562,  0.31326021, -1.10829086,  0.89261624],
        [-0.02795985,  1.57876294,  0.96493728,  0.35332572],
        [-0.06261115,  0.78104457,  1.43546289, -0.63733497]],

       [[ 0.5025725 ,  1.50425285,  1.27716007, -1.5301953 ],
        [-1.01171051,  0.54940159,  0.06894324,  0.69816051],
        [ 1.13271901,  0.07814539,  0.30667068,  2.19694921]]])

In [56]:
#We can still use a random.random() to return the next random floating point

### Exercise

In [57]:
#Generate one randome Number using randint, random and randn
np.random.randint(10)
np.random.rand()
np.random.randn()

2.0964314631420162

In [58]:
#Generate 10 random numbers using randint, random and randn

In [59]:
#create random list with range
np.random.randint(1,50,size=10)
np.random.rand(10)
np.random.randn(10)

array([ 1.10261902, -0.40546295,  1.90197597, -0.60133114,  2.60164313,
       -2.04929071, -1.85732542, -1.55356327, -0.7845093 , -1.74186697])

In [60]:
#Generate a 10x10 matrix of random numbers using randint, random and randn
np.random.randint(1,100,size=(10,10))
np.random.rand(10,10)
np.random.randn(10,10)

array([[-1.1183445 ,  0.12642052, -1.44730426, -0.14749576,  0.04768958,
        -0.53462546, -2.33578163,  1.44167682, -0.9092493 ,  0.78316818],
       [-0.25585512, -0.00494792,  1.50324771, -0.90920817, -0.30360582,
         0.24354255, -0.34605395, -1.36884954,  0.4493365 ,  0.49978241],
       [-2.24597794,  0.59795567, -0.49985007, -0.43968497, -0.99702413,
        -0.64983925, -0.17707798,  0.41562004, -0.20663843, -0.36598706],
       [ 1.07929225, -1.95291993,  2.0768404 ,  0.53810595,  1.1327892 ,
        -0.28784108,  0.92367182, -1.02755654, -0.95635631,  1.33876897],
       [-2.44780026,  0.83035936,  0.06079172, -0.703134  , -0.44250746,
         1.88033346,  1.66106744, -0.5366158 ,  1.95593207, -0.10652237],
       [ 0.35940088, -0.98423442, -1.19809449, -0.38822642,  0.46088992,
         1.39525647, -0.7561164 , -1.46233694, -0.70589539,  0.13779415],
       [-0.50290756, -1.13253284, -0.74931204,  0.46720754,  0.70572514,
        -0.15171704,  0.5287464 ,  0.17264766

In [61]:
## Project
Create a random number generator for lottery and see if you would ever win

SyntaxError: invalid syntax (<ipython-input-61-4a9421e997c1>, line 2)

In [ ]:
https://docs.python.org/2/library/random.html
https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.randn.html
https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.randint.html
https://numpy.org/doc/stable/reference/random/generated/numpy.random.randn.html
https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html
https://numpy.org/doc/1.16/reference/routines.random.html